import {test, expect, Page} from '@playwright/test';


test('CvmStJean', async ({ page }) => {
  await page.goto('http://localhost:4200/');
  await page.getByTestId('01e15797-1439-4a3e-a27e-57c7f39cea6f').click();
  await page.getByTestId('selectAllHomePlayer').click();
  await page.getByTestId('selectAllAwayPlayer').click();
  await page.getByTestId('closeLineup').click();

  // #Play 1
  await page.getByTestId('homeReceiveKickoff').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('returner-player-5').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').dblclick();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('tackler-player-4').click();
  await page.getByTestId('tackler-player-7').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();

  // Play 2
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-5').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();

  // Play 3
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-5').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();  
  await page.getByTestId('finishTagging').click();

  // Play 4
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('rusher-player-0').getByRole('button', { name: '0' }).click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('rusher-player-88').click();
  await page.getByTestId('rusher-player-0').getByRole('button', { name: '0' }).click();
  await page.getByTestId('finishTagging').click();

  // Play 5
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('finishTagging').click();

  // Play 6
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn6').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();

  // Play 7
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('battedDown-player-3').click();
  await page.getByTestId('finishTagging').click();

  // Play 8
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();

  // Play 9
  await page.getByTestId('qBSack').click();
  await page.getByTestId('tackler-player-3').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();

  // Play 10
  await page.getByTestId('punt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByRole('button', { name: 'Finish Tagging this Play' }).click();

  // Play 11
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();

  // Play 12
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();

  // Play 13
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('tackler-player-4').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('halfTheDistance').click();
  await page.getByTestId('penaltySpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('savePenalty').click();

  // Play 14

  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-4').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();

  // Play 15
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-4').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();

  // Play 16
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-7').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn6').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();
 
  // Play 17
  await page.getByTestId('punt').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('tackler-player-4').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();

  // Play 18

  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-5').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect STJEAN to have 6 pts

  // Play 19
  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  //expect STJEAN to have 7 pts

  // Play 20
  await page.getByTestId('homeKickoff').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-7').click();
  await page.getByTestId('tackler-player-6').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').dblclick();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').dblclick();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();

  // Play 21
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();

  // Play 22
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();

  // Play 23
  await page.getByTestId('punt').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('returner-player-41').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('block').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('returnTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();

  // Play 24

  await page.getByTestId('incompletePass').click();
  await page.locator('#mat-button-toggle-58').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn6').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher').getByLabel('Player').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').dblclick();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('fgAttempt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('noGood').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('return').click();
  await page.getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();

  
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn0').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').dblclick();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard10').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-4').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  //deuxieme quart start
  await page.getByTestId('changeQuarter').click();
  await page.getByTestId('fgAttempt').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('finishTagging').click();
  //expect cvm to have 3 pts


  await page.getByTestId('conversion2pts').click();
  await page.getByTestId('qBSack').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn0').click();
  await page.getByTestId('wheelBtnEffacer').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();

  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();


  await page.getByTestId('interception').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('interceptor-player-21').click();
  await page.getByTestId('tackler-player-1').click();
  await page.getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect cvm to have 9 pts
  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  //expect cvm to have 10 pts
  await page.getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('homeReceiveKickoff').click();


  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('returner-player-5').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('tackler-player-4').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-5').click();
  await page.getByTestId('tackler-player-9').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('qBSack').click();
  await page.getByTestId('tackler-player-3').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('tackler-player-3').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-5').click();
  await page.getByTestId('tackler-player-9').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('qBSack').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').dblclick();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('punt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelOk').click();
  await page.getByRole('button', { name: 'Finish Tagging this Play' }).click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-4').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-4').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();

  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').dblclick();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();  
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();

  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('penaltyForHome').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('loosDown').click();
  await page.getByTestId('savePenalty').click();


  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn0').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn0').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('penaltyAfterPlay').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard10').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('fgAttempt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('mainBack').click();
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-5').click();

  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('homeKickoff').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-4').click();
  await page.getByTestId('tackler-player-2').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('fumble').click();
  await page.getByTestId('recoveredByHome').click();
  await page.getByTestId('forceFumble-player-1').click();
  await page.getByTestId('fumbleRecovered-player-1').click();
  await page.getByTestId('recoveredOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn0').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();

  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect st-jean to have 20

  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('homeKickoff').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();

  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();  


  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').dblclick();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();

  // END OF FIRST HALF
  await page.getByTestId('changeQuarter').click();
  await page.getByTestId('saveEndHalf').click();

  // START OF SECOND HALF

  await page.getByTestId('homeKickoff').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn6').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-4').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-14').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('punt').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('returner').getByLabel('Player').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  

  await page.getByRole('button', { name: 'Finish Tagging this Play' }).click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();

  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();

  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect st-jean to have 26 pts
  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  //expect st-jean to have 28 pts
  await page.getByTestId('homeKickoff').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler').getByLabel('Player').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('tackler-player-43').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.locator('#mat-button-toggle-2643').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.locator('#mat-button-toggle-2649').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('yard15').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('fumble').click();
  await page.getByTestId('recoveredByHome').click();
  await page.getByTestId('forceFumble-player-1').click();
  await page.getByTestId('fumbleRecovered-player-1').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();

  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();


  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('yard15').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();

  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect st-jean to have 34 pts

  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  //expect st-jean to have 35 pts

  await page.getByTestId('homeKickoff').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returner-player-2').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-4').click();
  await page.getByTestId('selectGain').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('touchdown').click();
  //ex cvm to have 16 pts
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('conversion2pts').click();
  await page.getByTestId('pass').click();
  await page.getByTestId('noGood').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-7').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('homeReceiveKickoff').click();

  
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('returner-player-5').click();

  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.locator('#mat-button-toggle-3631').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();

  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('punt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('safetyKicking').click();
  await page.getByRole('button', { name: 'Finish Tagging this Play' }).click();
  //expect cvm to have 18 pts

  
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishResume').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn6').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();

//change quarter
  await page.getByTestId('changeQuarter').click();

  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-8').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('savePenalty').click();


  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-3').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn0').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect cvm to have 24 pts

  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  //expect cvm to have 25 pts


  await page.getByTestId('homeReceiveKickoff').click();
  await page.locator('#mat-button-toggle-4318').click();
  await page.locator('#mat-button-toggle-4322').click();
  await page.getByTestId('caughtOn').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();

  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('penaltyForAway').click();
  await page.getByTestId('yard15').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('savePenalty').click();

  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn8').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.locator('#mat-button-toggle-4658').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelCancel').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('preSnapPenalty').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('repeatLastDown').click();
  await page.getByTestId('yard5').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect st-jean to have 41 pts

  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();


  await page.getByTestId('homeKickoff').click();
  await page.getByTestId('kicker-player-1').click();
  await page.getByTestId('returnedTo').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('returner-player-4').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn6').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();


  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('yard15').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('fumble').click();
  await page.getByTestId('recoveredByHome').click();
  await page.getByTestId('forceFumble-player-1').click();
  await page.getByTestId('fumbleRecovered-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectGain').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn7').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer').getByLabel('Player').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.locator('#mat-button-toggle-5293').click();
  await page.getByTestId('selectGain').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectGain').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('tackler-player-5').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();

  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-1').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.locator('#mat-button-toggle-5550').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtnPlusMoins').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn4').click();
  await page.getByTestId('wheelBtn5').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashM').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('hashR').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn3').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('completePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('receiver-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn2').click();
  await page.getByTestId('wheelBtn6').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('selectSpot').getByTestId('wheelEdit').click();
  await page.getByTestId('wheelBtn1').click();
  await page.getByTestId('wheelBtn9').click();
  await page.getByTestId('wheelOk').click();
  await page.getByTestId('hashL').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('incompletePass').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('passer-player-8').click();
  await page.getByTestId('penalty').click();
  await page.getByTestId('firstDown').click();
  await page.getByTestId('yard15').click();
  await page.getByTestId('savePenalty').click();
  await page.getByTestId('run').click();
  await page.getByTestId('rusher-player-2').click();
  await page.getByTestId('touchdown').click();
  await page.getByTestId('finishTagging').click();
  //expect cvm to have 31 pts

  await page.getByTestId('extraPt').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('good').click();
  await page.getByTestId('finishTagging').click();
  //expect cvm to have 32 pts

  await page.getByTestId('homeReceiveKickoff').click();
  await page.getByTestId('kicker-player-6').click();
  await page.getByTestId('returner-player-5').click();
  await page.getByTestId('returner-player-5').click();
  await page.getByTestId('finishTagging').click();
  await page.getByTestId('changeQuarter').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByTestId('saveEndGame').click();
  const page1 = await page1Promise;
  await page1.getByRole('heading', { name: '42' }).click();
  await page1.getByRole('heading', { name: '32' }).click();
  
});